compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: bf16
num_processes: 2
gpu_ids: "0,1"

kwargs_handlers:
  - accelerate.utils.DistributedDataParallelKwargs:
      find_unused_parameters: true     # you still need this for LoRA
      static_graph: true               # <-- this is what you asked for
