# Dr GRPO Configuration for ToSSim Syntax Training with FSDP+vLLM Hybrid
# Following the specifications for syntax-only "boot-camp" training with real environment interaction

# Model settings
model_name: "unsloth/Qwen2.5-Coder-32B-Instruct"  # Can be replaced with Gemma-3-27B or others
learning_rate: 0.00005  # 5e-5 with linear warmup to cosine decay
min_learning_rate: 0.00001  # 1e-5 final LR after cosine decay
warmup_ticks: 100
gradient_clip_norm: 1.0

# FSDP + vLLM hybrid settings
sync_every: 10  # Sync FSDP weights to vLLM every N ticks
batch_size: 90  # ~30 games × 3 active seats
max_tokens_per_gen: 96
temperature: 0.8
top_p: 0.9
const_baseline: 0.0  # β = 0 (no baseline)

# Environment settings
num_concurrent_games: 30  # Number of ToSSim games running concurrently
active_seats_per_game: 3  # Round-robin selection of active agents per game

# Training settings
max_ticks: 5000  # Should converge much faster for instruction-tuned models
save_ticks: 500
log_ticks: 10
eval_ticks: 100
output_dir: "dr_grpo_syntax_output"

# Monitoring & early stopping
early_stop_parse_rate: 0.99  # 99% parse accuracy
early_stop_consecutive_ticks: 1000  # for 1k consecutive ticks

# Optional verbosity penalty (enable if think tokens trend upward after high parse rate)
enable_verbosity_penalty: false  # Start disabled
verbosity_penalty_rate: 0.05  # -0.05 per token over max_think_tokens
max_think_tokens: 64  # NOWAIT principle: shorter reasoning often suffices

# Hardware settings (FSDP)
tensor_parallel_size: 2  # For 2×H100 setup (vLLM)
dtype: "bfloat16"
max_model_len: 2048
trust_remote_code: true

# Phase-aware rewards for emergent misalignment research
# +1: Valid XML and phase-legal action
#  0: Valid XML but phase-illegal action (preserve misalignment potential)
# -1: Malformed XML

# Expected convergence with environment interaction
# Modern 27B+ instruction-tuned models start around 85% parse accuracy
# Should reach 99%+ within 2k-5k ticks (~1 hour on 2×H100)
# Legal action rate should be 70-90% initially, improving to 95%+
expected_convergence_ticks: 3000
expected_initial_parse_rate: 0.85
expected_initial_legal_rate: 0.80 