chat_history_lines: null      # keep full previous-day chat (no pruning yet)

# Token budgets
per_agent:
  discussion: 50       # multiplied by living agents
  nomination: 50       # multiplied by living agents

defense: 50            # defendant only
judgement:
  total: 50           # global budget
  tail_after_all_votes: 50

last_words:
  defendant: 40
  post_reveal_global: 30

night_channel: 30       # per voice channel 
pre_night: 20            # explicit pre-night phase budget (now nonzero) 