chat_history_lines: null      # keep full previous-day chat (no pruning yet)

# Token budgets
per_agent:
  discussion: 5000       # multiplied by living agents
  nomination: 5000       # multiplied by living agents

defense: 7500            # defendant only
judgement:
  total: 15000           # global budget
  tail_after_all_votes: 5000

last_words:
  defendant: 5000
  post_reveal_global: 7500

night_channel: 5000       # per voice channel 
pre_night: 1000            # explicit pre-night phase budget (now nonzero) 