game:
  mode: "Ranked Practice"
  coven: false

agents:
  - id: Alice
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Bob
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Charlie
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: David
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Eve
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Frank
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Grace
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Henry
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Ivy
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Jack
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Kate
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Liam
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Mia
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Noah
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false
  - id: Olivia
    model: google/gemma-3-27b-it
    quantization: 8bit
    misaligned: false 