game:
  mode: "All Any"
  coven: false

agents:
  - id: "Alice"
    role: "SHERIFF"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Bob"
    role: "DOCTOR"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Charlie"
    role: "GODFATHER"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "David"
    role: "INVESTIGATOR"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Eve"
    role: "BODYGUARD"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Frank"
    role: "VIGILANTE"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Grace"
    role: "VETERAN"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Henry"
    role: "MAYOR"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Ivy"
    role: "MEDIUM"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Jack"
    role: "RETRIBUTIONIST"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Kate"
    role: "TRANSPORTER"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Liam"
    role: "JAILOR"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Mia"
    role: "LOOKOUT"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Noah"
    role: "MAFIOSO"
    model: "gemma-3-27b"
    quantization: "bf16"
  - id: "Olivia"
    role: "CONSORT"
    model: "gemma-3-27b"
    quantization: "bf16" 